import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Router from "next/router";
import { useEffect } from 'react'

const Home: NextPage = () => {

  
  return (
    <div>
      <Head>
        <title>Bondaf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo_symbol_dark.svg" />
      </Head>
      <div onLoad={()=>Router.push('/users')}>
      </div>

    </div>
  )
  
  
}

export default Home
